# Generated by Django 3.2.8 on 2021-10-20 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('introduction', models.TextField(max_length=500)),
                ('section_one_title', models.CharField(max_length=100)),
                ('section_one_text', models.TextField(max_length=1000)),
                ('section_one_picture', models.CharField(max_length=100)),
                ('section_one_activity', models.TextField(max_length=500)),
                ('section_two_title', models.CharField(max_length=100)),
                ('section_two_text', models.TextField(max_length=1000)),
                ('section_two_picture', models.CharField(max_length=100)),
                ('section_two_activity', models.TextField(max_length=500)),
                ('summary', models.TextField(max_length=500)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to=settings.AUTH_USER_MODEL)),
                ('topics', models.ManyToManyField(related_name='lessons', to='topics.Topic')),
            ],
        ),
    ]
