# Generated by Django 3.2.8 on 2021-10-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='section_one_picture',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='section_two_picture',
            field=models.CharField(max_length=250),
        ),
    ]
